import pygame_gui
from client.ihm.common.component import Component
from typing import Any

class GamesList(Component):
    pygame_manager: Any
    container: Any
    games: Any
    def __init__(self, pygame_manager: pygame_gui.UIManager, container: Component, games: list, pos_x: int, pos_y: int) -> None: ...
    gui_element: Any
    def render(self) -> None: ...
    text: Any
    def modify_text(self, text: str) -> None: ...
    def add_even(self, game: tuple, pos: int) -> None: ...
    def add_odd(self, game: tuple, pos: int) -> None: ...
