import pygame_gui
from client.ihm.common.component import Component
from typing import Any

class PlayersList(Component):
    pygame_manager: Any
    container: Any
    players: Any
    def __init__(self, pygame_manager: pygame_gui.UIManager, container: Component, players: list, pos_x: int, pos_y: int) -> None: ...
    gui_element: Any
    def render(self) -> None: ...
    text: Any
    def modify_text(self, text: str) -> None: ...
    def add_even(self, player: str, pos: int) -> None: ...
    def add_odd(self, player: str, pos: int) -> None: ...
