from common import Profile as Profile
from common.interfaces.i_comm_calls_ihm_main import I_CommCallsIHMMain

class CommCallsIHMMain_Impl(I_CommCallsIHMMain):
    def close_waiting_game(self) -> None: ...
    def display_user_profile(self, profile: Profile) -> None: ...
    def start_waiting_screen(self) -> None: ...
    def launch_spectate_game(self) -> None: ...
    def join_game_as_player(self) -> None: ...
    def launch_main(self) -> None: ...
    def notify_new_connected_user(self) -> None: ...
    def player_join_game(self) -> None: ...
    def notify_new_game(self) -> None: ...
    def notify_game_deleted(self) -> None: ...
