import abc
from abc import ABC, abstractmethod

class I_CommCallsIHMGame(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def notify_new_spectator(self) -> None: ...
    @abstractmethod
    def spectator_quits_game(self) -> None: ...
    @abstractmethod
    def update_game(self) -> None: ...
    @abstractmethod
    def notify_new_message(self) -> None: ...
