import abc
from abc import ABC, abstractmethod
from common.data_structures.profiles import Profile as Profile

class I_CommCallsIHMMain(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def close_waiting_game(self) -> None: ...
    @abstractmethod
    def display_user_profile(self, profile: Profile) -> None: ...
    @abstractmethod
    def start_waiting_screen(self) -> None: ...
    @abstractmethod
    def launch_spectate_game(self) -> None: ...
    @abstractmethod
    def join_game_as_player(self) -> None: ...
    @abstractmethod
    def launch_main(self) -> None: ...
    @abstractmethod
    def notify_new_connected_user(self) -> None: ...
    @abstractmethod
    def player_join_game(self) -> None: ...
    @abstractmethod
    def notify_new_game(self) -> None: ...
    @abstractmethod
    def notify_game_deleted(self) -> None: ...
