import abc
import uuid as uuid_lib
from abc import ABC, abstractmethod
from common import LocalGame as LocalGame, Player as Player, Profile as Profile, PublicGame as PublicGame
from common.data_structures.user import User as User
from typing import List

class I_IHMMainCallsData(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def get_local_game_id(self) -> uuid_lib.UUID: ...
    @abstractmethod
    def get_profile(self) -> Profile: ...
    @abstractmethod
    def create_new_profile(self, user: User) -> None: ...
    @abstractmethod
    def create_game(self, name: str, tiles: int) -> LocalGame: ...
    @abstractmethod
    def export_current_profile(self, destination_path: str) -> None: ...
    @abstractmethod
    def import_profile(self, path: str) -> Profile: ...
    @abstractmethod
    def edit_current_profile(self, profile: Profile) -> None: ...
    @abstractmethod
    def get_connected_players(self) -> List[Player]: ...
    @abstractmethod
    def get_public_games(self) -> List[PublicGame]: ...
    @abstractmethod
    def disconnect_from_app(self) -> None: ...
    @abstractmethod
    def disconnect_server(self) -> None: ...
    @abstractmethod
    def connect_to_app(self, nickname: str, password: str) -> None: ...
