import unittest

def callback(): ...

class Transport:
    def get_extra_info(self, s): ...

class TestIO(unittest.TestCase):
    def test_on(self) -> None: ...
    def test_connection_made(self) -> None: ...
    def test_connection_lost(self) -> None: ...
