import pygame.event
import pygame_gui.core
import typing
from typing import Any

class Component:
    manager: Any
    width: Any
    height: Any
    pos_x: Any
    pos_y: Any
    container: Any
    gui_element: Any
    controller: Any
    def __init__(self, pygame_manager: pygame_gui.UIManager, width: Any | None = ..., height: Any | None = ..., pos_x: Any | None = ..., pos_y: Any | None = ...) -> None: ...
    def set_controller(self, controller: typing.Any): ...
    def render(self) -> None: ...
    def handle_event(self, event: pygame.event.Event) -> None: ...
    def get_gui_element(self) -> pygame_gui.core.UIElement: ...
    def get_width(self) -> int: ...
    def get_height(self) -> int: ...
    def get_pos_x(self) -> int: ...
    def get_pos_y(self) -> int: ...
    def set_width(self, value: int) -> None: ...
    def set_height(self, value: int) -> None: ...
    def set_pos_x(self, value: int) -> None: ...
    def set_pos_y(self, value: int) -> None: ...
