import pygame_gui
from client.ihm.common.ui_renderer import UIRenderer
from client.ihm.common.view import View as View
from typing import Any

FPS: int
DIVIDER: float

class PyGameController:
    ui: Any
    def __init__(self) -> None: ...
    def show_view(self, view: View) -> None: ...
    def get_ui_manager(self) -> pygame_gui.UIManager: ...
    def get_ui_renderer(self) -> UIRenderer: ...
    def run_main_loop(self) -> None: ...
