import pygame_gui
import typing
from typing import Any

class UIRenderer:
    current_view: Any
    window_size: Any
    background: Any
    pygame_manager: Any
    window_surface: Any
    def __init__(self) -> None: ...
    def show_view(self, view: typing.Any): ...
    def handle_event(self, event) -> None: ...
    def init_window_size(self): ...
    def reset_background(self) -> None: ...
    def init_background(self): ...
    def handle_game_loop(self, time_delta) -> None: ...
    def get_pygame_manager(self) -> pygame_gui.UIManager: ...
